version: '3'

networks:
  payment-order-network:
    name: payment-order-network
    driver: bridge
    external: false
  bank-network:
    name: bank-network
    driver: bridge
    external: true

services:
  db:
    container_name: payment-order-db
    image: "postgres"
    ports:
      - "5433:5432"
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER
      interval: 10s
      timeout: 3s
      retries: 3
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - payment-order-network

  app:
    container_name: payment-order-app
    build: .
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://payment-order-db/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1111
      JDBC_DRIVER: org.postgresql.Driver
      JDBC_URL: jdbc:postgresql://payment-order-db:5432/postgres
      JDBC_USERNAME: postgres
      JDBC_PASSWORD: 1111
      WEBCLIENT_MAX_SIZE: 16777216
      WEBCLIENT_BASE_URL_CUSTOMER: http://customer-app:8080/api/v1
      WEBCLIENT_TIMEOUT_MILLIS: 5000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - bank-network
      - payment-order-network

  pgadmin:
    container_name: payment-order-pgadmin
    image: dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5051:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - payment-order-network

volumes:
  db-data:
    name: payment-order-db-data
  pgadmin-data:
    name: payment-order-pgadmin-data
