version: '3'

services:
  db:
    container_name: payment_order_db
    image: "postgres"
    ports:
      - "5433:5432"
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER
      interval: 10s
      timeout: 3s
      retries: 3
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    container_name: payment_order_app
    build: .
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1111
      JDBC_DRIVER: org.postgresql.Driver
      JDBC_URL: jdbc:postgresql://customer_db:5432/postgres
      JDBC_USERNAME: postgres
      JDBC_PASSWORD: 1111
    depends_on:
      db:
        condition: service_healthy

  pgadmin:
    container_name: payment_order_pgadmin
    image: dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5051:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  db_data:
  pgadmin_data:
