apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-configmap
  namespace: kafka
data:
  kafka-jmx-opts: "-Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=$HOSTNAME -Djava.net.preferIPv4Stack=true"