kind: PersistentVolume
apiVersion: v1
metadata:
  name: payment-order-pv-volume
  labels:
    type: local
    app: payment-order-db
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/payment-order-db"