apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-order-app-env
  namespace: payment-order
data:
  database-url: payment-order-pgpool-service
  spring-datasource-url: jdbc:postgresql://payment-order-pgpool-service/postgres
  jdbc-driver: org.postgresql.Driver
  webclient-max-size: '16777216'
  webclient-base-url-customer: http://customer-app-service.customer:8082/api/v1
  webclient-timeout-millis: '5000'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-order-app
  namespace: payment-order
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-order-app
  template:
    metadata:
      labels:
        app: payment-order-app
    spec:
      containers:
        - name: payment-order-app
          image: vadimstepuro/payment-order-app
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: payment-order-app-env
                  key: spring-datasource-url

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: payment-order-db-secret
                  key: payment-order-db-root-username

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: payment-order-db-secret
                  key: payment-order-db-root-password

            - name: JDBC_DRIVER
              valueFrom:
                configMapKeyRef:
                  name: payment-order-app-env
                  key: jdbc-driver

            - name: JDBC_URL
              valueFrom:
                configMapKeyRef:
                  name: payment-order-app-env
                  key: spring-datasource-url

            - name: JDBC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: payment-order-db-secret
                  key: payment-order-db-root-username

            - name: JDBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: payment-order-db-secret
                  key: payment-order-db-root-password

            - name: WEBCLIENT_MAX_SIZE
              valueFrom:
                configMapKeyRef:
                  name: payment-order-app-env
                  key: webclient-max-size

            - name: WEBCLIENT_BASE_URL_CUSTOMER
              valueFrom:
                configMapKeyRef:
                  name: payment-order-app-env
                  key: webclient-base-url-customer

            - name: WEBCLIENT_TIMEOUT_MILLIS
              valueFrom:
                configMapKeyRef:
                  name: payment-order-app-env
                  key: webclient-timeout-millis
---
apiVersion: v1
kind: Service
metadata:
  name: payment-order-app-service
  namespace: payment-order
spec:
  type: NodePort
  selector:
    app: payment-order-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
      nodePort: 30001