kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: payment-order-pv-claim
  namespace: payment-order
  labels:
    app: payment-order-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi